version: '3'
services:
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
      - ./db-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: ./mywordpress/Dockerfile
    ports:
      - "8080:80"
    volumes: 
      - ./mywordpress:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secretpassword
      MYSQL_DB: sampledb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - mysql:mysql
    ports:
        - 8000:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root

volumes:
  data: